version: '3'

services:
  job-controller:
    image: job-controller:latest
    container_name: job_controller
    ports:
      - "8081:8081"

  task-scheduler:
    image: task-scheduler:latest
    container_name: task-scheduler

  adder:
    image: standard-worker:latest
    container_name: adder
    environment:
      WORKER_ID: adder_1
      WORKER_TYPE: ADDITION
      WORKER_DELAY: 10
      READS_TOPIC: addition

  mulitiplier:
    image: standard-worker:latest
    container_name: mulitiplier
    environment:
      WORKER_ID: mulitiplier_1
      WORKER_TYPE: MULTIPLICATION
      WORKER_DELAY: 10
      READS_TOPIC: multiplication

  divider:
    image: standard-worker:latest
    container_name: divider
    environment:
      WORKER_ID: divider_1
      WORKER_TYPE: DIVISION
      WORKER_DELAY: 10
      READS_TOPIC: division

  exponent:
    image: standard-worker:latest
    container_name: exponent
    environment:
      WORKER_ID: exponent_1
      WORKER_TYPE: EXPONENT
      WORKER_DELAY: 10
      READS_TOPIC: exponent

  superworker:
    image: super-worker:latest
    container_name: superworker
    environment:
      WORKER_ID: superworker_1
      WORKER_TYPE: SUPER
      WORKER_DELAY: 10
      READS_TOPIC: exponent

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka_broker_1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    hostname: kafka_broker_1
    container_name: kafka_broker_1
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED: INTERNAL://kafka_broker_1:9092,EXTERNAL://localhost:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_broker_1:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 101

  kafka_broker_2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29093:29093"
    hostname: kafka_broker_2
    container_name: kafka_broker_2
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED: INTERNAL://kafka_broker_2:9093,EXTERNAL://localhost:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_broker_2:9093,EXTERNAL://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 102

  kafka_broker_3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29094:29094"
    hostname: kafka_broker_3
    container_name: kafka_broker_3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED: INTERNAL://kafka_broker_3:9094,EXTERNAL://localhost:29094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_broker_3:9094,EXTERNAL://localhost:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 103
