spring:
  profiles:
    active: docker
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka_broker_1:9092, kafka_broker_2:9093, kafka_broker_3:9094
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: ${GROUP_ID}
    topic-names:
      compute-task: compute-task
      completed-task: completed-task
      addition: addition
      multiplication: multiplication
      division: division
      exponent: exponent
      superworker: superworker
logging:
  level:
    root: info
    com.mpdgr: debug
instance:
  properties:
    worker:
      id: ${WORKER_ID}
      type: ${WORKER_TYPE}
      operation: ${WORKER_OPERATION}
      delay: ${WORKER_DELAY}
      reads-topic: ${READS_TOPIC}
      superworker: false