spring:
  profiles:
    active: local
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: kafka_broker_1:9092, kafka_broker_2:9093, kafka_broker_3:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: task-scheduler
      poll-interval: 20
#    properties:
#      acks: -1  #todo: chyba nie działa
#      retries: 50
#    admin:
#      properties:
#        client.id: adm
    topic:
      compute-task: compute-task
      completed-task: completed-task
      addition: addition
      multiplication: multiplication
      division: division
      exponent: exponent
      superworker: superworker
      superworker-state: superworker-state
logging:
  level:
    root: info
    com.mpdgr: trace
computing:
  properties:
    assist: 2
instance.properties.worker.id: ${WORKER_ID}